
$(document).ready(function(){
    var x;
    var myCards=[
   {"name":"The Ace of Cups","imgsrc":"img/Cups/Cups/Ace.jpg","desc":"The aces indicate beginning of something new, when it is cups it is related to the matters of the heart. You are ready to start a new life with your loved ones. In some cases, someone will walk into your life, a new love. Your relationships will be full of love and abundance. You will have plenty of satisfaction on the personal front. Your creativity will be sparked so you have all the rights to be happy and excited. You will be aligned with your spiritual truth and you will feel one with the spirit."},
                  {"name":"The Two of Cups","imgsrc":"img/Cups/Cups/2.jpg","desc":"You are developing a strong connection with someone, perhaps that person you love the most. There is immense passion and understanding between both of you. The two of you will be very much in love with each other. This connection is meant to be. People experiencing trouble with their loved one can expect peace to be restored and appearance of this card gives them a chance to reconnect. You have accepted the two facets of your personality and are in harmony with it."},  
                  {"name":"The Three of Cups","imgsrc":"img/Cups/Cups/3.jpg","desc":"A celebration is on the way, wedding, birth, reunion, family connection. You will be resourceful.  You have found a way that spurs your heart and now you can express yourself freely. A collaboration will be successful. Nonetheless, it represents celebration and you will have every reason to celebrate. "},
                  {"name":"The Four of Cups","imgsrc":"img/Cups/Cups/4.jpg","desc":"There is a energy of stagnation. You feel stuck in some parts of your life. There is a feeling of unfulfilment and lack. That spark that was once there needs to be reignited. Demotivation has taken toll on you. Try to face the reality of life that trying to escape it. This will make you harbor self-criticizing, self-limiting beliefs so you need to be watchful of what you tell yourself. "},
                  {"name":"The Five of Cups","imgsrc":"img/Cups/Cups/5.jpg","desc":"The five depicts loss in one direction; you need to change your attention to the other.  Unexpected financial loses are foreseen. You are not satisfied, your expectations have not been met. It is now time you leave this situation and move on to healthy one. It is an end of unhappy situation. Don’t mourn for long. Gather yourself up, since all is not lost. Another opportunity awaits.  "},
                  {"name":"The Six of Cups","imgsrc":"img/Cups/Cups/6.jpg","desc":"This card tells that you are undergoing nostalgia. There are times that you seem to have been missing. Somebody from your past is likely to show up. The answer to your question also lies in these past moments. You have to go back down the memory lane to recapture those moments and use them in present now. Change in perception will benefit you a lot. The obstacles will disappear and you will open yourself to love. "},
                  {"name":"The Seven of Cups","imgsrc":"img/Cups/Cups/7.jpg","desc":"A difficult choice appears in front of you. Everything will seem similar and comfortable, you need to use your will to see what is what in order to make the right choice. All is not as it seems. Don’t be unrealistic and explore your options. Similar thing goes for your personal life where in you need to decide as in what it that you want. Keep yourself open for the possibilities. "},
                  {"name":"The Eight of Cups","imgsrc":"img/Cups/Cups/8.jpg","desc":"Devotion and commitment is required towards whatever you have undertaken.  You need to battle the lack of self- belief. Uncertainties of any kind are stopping the flow of life energy through you. This will not let you achieve what you really want to. You should leave a work/ situation that no longer serves you. You have outgrown it now and need to find a new place that fits your need. Encourage yourself in the direction of achievement."},
                  {"name":"The Nine of Cups","imgsrc":"img/Cups/Cups/9.jpg","desc":"Fortune shines upon you. This card promises success in the field of business and finances. A very rewarding is to come; you will have all the material comfort. You will be involved in buying and selling of properties.  Open your heart to the happenings in your personal life. You will finally receive what you have wished for. Wishes will come true."},
                  {"name":"The Tens of Cups","imgsrc":"img/Cups/Cups/10.jpg","desc":"Opening of communication between you and the ones who are close to you. This will give you strength as you will be supported. You now have emotional maturity. You will receive recognition for your work. The 10 shows a good omen to carry on the family business. Life is harmonious and the plans have been completed."},
                  {"name":"The Page of Cups","imgsrc":"img/Cups/Cups/page.jpg","desc":"It represents a person who is new to the worldly experiences and is naïve. He/she could be too shy and tends to remain amongst themselves. Are intuitive and have spiritual inclination. Soft in nature they are sensitive and have low self esteem sometimes. When it comes to work you have to be watch over your finances. Revise your work documents again and don’t let people dominate you. The hurtful past experiences have left you feel vulnerable when it comes to love relations. A new relationship or a new person will walk into your life and will bring joy."},
                  {"name":"The Knight of Cups","imgsrc":"img/Cups/Cups/Knight.jpg","desc":"Someone in your life is looking for love. It represents a person who has a sensitive soul and is very romantic. At the same time this person is afraid of making commitment.  This person loves to voyage. A change in your work can help move your finances. Stick to your chosen career and try to be more decisive Use your imagination and creativity and you will attract a relationship which will set you free. "},
                  {"name":"The Queen of Cups","imgsrc":"img/Cups/Cups/Queen.jpg","desc":"A woman who is full of compassion and senses all the emotional currents. Use your intuitions when it comes to dealing with the finances. Be flexible and changes in the workplace are likely. You could also get the opportunity to work in the field concerning women. The Queen of Cups is a very nurturing person who believes in her heart and is trustworthy. So should you when it comes to handling the relationships."},
                  {"name":"The King of Cups","imgsrc":"img/Cups/Cups/King.jpg","desc":"It represents a person who is calm in all the situations. This person chooses to help others to heal him. In work, keep your emotional judgment aside as it might be hampering your decision making. You will have success in all your endeavours if you take control in your hands. In relationships, trust, faith and honesty is required to move forward. Be aware of your partner or you keeping secrets from each other. Opening up to each other will bring you close."},
{"name":"The Fool","imgsrc":"img/Major Arcana Pictures/0. The Fool.jpg","desc":"The Fool represents the person who is innocent at heart and is swayed by simple joys of life. This a time for you to have new beginnings and nothing can harm you. Pay attention to details and encourage yourself upon learning. On the work front, you will get new opportunities but financially you should learn to handle your money. Expect the unexpected changes and unconventional people will enter your life. The Fool embarks the beginning of a new chapter. In love, the Fool represents the early stages of romance. Follow your heart and be guided by your emotions and feelings."},
                    {"name":"The Magician","imgsrc":"img/Major Arcana Pictures/1. The Magician.jpg","desc":"A sense of purpose and strength will take birth in your life. Magician represents new optimism, new endeavors and is also a good sign to begin a new enterprise. Be careful of manipulative people and in work someone will try to go behind your back so beware.  Try not to get in ego battles with your partner and seek mutual understanding. You have a good control and influence over your life. You have the potential, the skillset and the ability to make accomplish your work. Be secretive while you work on certain projects as this will keep you away from the harm of energies of other people."},
                    {"name":"The High Priestess","imgsrc":"img/Major Arcana Pictures/2. The High Priestess.jpg","desc":"This is a card of intuition. The card tells that you have the wisdom and the light to achieve the purpose of your life. You know what the right path to take is, you can see the road that lies ahead clearly, this card tells you to trust your instincts and follow it. In man’s reading it represents the most important woman in his life because it carries feminine energy with it. You must rely on your instincts. In every area of your life your instincts are the one that will save your day. Develop your psychic abilities and your memory. In love, listen to your feelings about that particular person. Trust your hunches!"},
                    {"name":"The Empress","imgsrc":"img/Major Arcana Pictures/3. The Empress.jpg","desc":"The figure in the card represents maternity and it symbolizes birth of new ideas, stability, good fortune, sense of self-worth, creativity. You have an excellent ability to listen to others and you are an empath. This will prove to be of great benefit to you. Utilize your talents in the most useful ways that will help others as well. In readings, this card signifies good health, healthy connections, commitment.  You have both emotional and mental support with you now, so take on your projects. You will be able to work well and in harmony with feminine energies around."},
                    {"name":"The Emperor","imgsrc":"img/Major Arcana Pictures/4. The Emperor.jpg","desc":"You should not refrain from presenting your true nature to the people around you which is leadership, authoritative in nature. This will help them rely on someone and not be directionless. Use your brain more constructively. This card represents a man with strong and upheld personality. He takes his responsibility with utmost severity. It defines a person in authority and in a woman’s readings this is the most important man in her life. In relationships, this man could be less emotionally demonstrative but very mature and financially a secure man. Achievements and honour is foretold perhaps some help of an influential person is required. "},
                    {"name":"The High Priest or Hierophant","imgsrc":"img/Major Arcana Pictures/5. The Hierophant.jpg","desc":"There is a dire requirement to make changes in your life. There is an urge in your life to know about the spiritual truths. The Hierophant develops intuition about your work and is a very encouraging card to let go of your past and advises you to be forgiving. You are in the process of developing your higher self. You may want to study astrology, religion. In relationships, you and your partner could work for shared cause. This relation will bring out the best in both of you. It represents stability and indicates marriage. Both the people will have very clear defined purpose. Try to understand life and believe the wisdom will come to you."},
                    {"name":"The Lovers","imgsrc":"img/Major Arcana Pictures/6. The Lovers.jpg","desc":" A person in your life will help you reunite with yourself.  The first thing that pops up in the mind when you see the Lovers card is ‘union’. In context to everything be it in personal life or professional life you will meet a person who you will be an equal to you. Develop a clear communication for these unions to be peaceful.  You will enjoy a harmonious relationship. Perhaps the Lovers card also represents that you will have to make a decision. Balance out the feminine and the masculine side of you. To embark a journey on the spiritual path you need to first identify yourself with your feminine or masculine counterpart, be androgynous.  "},
                    {"name":"The Chariot","imgsrc":"img/Major Arcana Pictures/The Chatiot.jpg","desc":"Take the control in your hands for in terms of work this card tells you to give your attention. Wait for sometime to see the results of your investments. You will win over a thing in your life, however stay humble. The four pillars of success are the use of physical, emotional, mental & spiritual strength. You have the access to all at once, realize and use it. Destiny is at work in your life and it will lead you to achieve greater things anything that you wish to go for will be done. Know that the power of pure intention is the strong strength that will empower you.  There is time for the right person to walk into your life. Focus on self-love and development. Embrace yourself before you enter into a relationship. "},
                    {"name":"The Strength","imgsrc":"img/Major Arcana Pictures/8.Strength.jpg","desc":"The woman in the card is seen opening lion’s mouth without hurting the lion. This signifies the strength and courage of the woman. Similarly, the appearance of this card in your reading tells you to be as courageous as this woman is and you can manage the animal nature with compassion. You can face the dwellings of your past, harness your personal power.  Take stand where you feel you’re being meek. It is time for you to change your attitude and develop self-confidence and fearlessness. Give up your defences and old patterns. Your love interest will help you change your outlook towards things and that too for good."},
                    {"name":"The Hermit","imgsrc":"img/Major Arcana Pictures/9. The Hermit.jpg","desc":"Do not be impulsive and resist taking sudden decisions. For you need advice of someone wiser and older than you. You are going through a period of introspection. Let go off the attachments to the material world for a while and focus on your inner self. Be more independent. Being with your own self for sometime will enhance your talents, skills, knowledge. You should be your priority and keep working on yourself. You can plan taking a solo trip to know what it felt like being with yourself. the answer to your question also lies how you use to identify yourself when you were a child. "},
                    {"name":"The Wheel of Fortune","imgsrc":"img/Major Arcana Pictures/10. The Wheel of Fortune.jpg","desc":"Your life is like seasons and seasons keep on changing. So good or bad make the best of it. Fortune will smile on you. The wheel will be turned in your favour. You need not do anything because the time is right; things will fall in place all by themselves. This is the result of your good deeds that you will be blessed in unimaginable ways. You must become aware of the patterns around you, don’t control the things instead try to identify yourself with the ebb & flow of the Universe."},
                    {"name":"The Justice","imgsrc":"img/Major Arcana Pictures/11. Justice.jpg","desc":"The Law of Cause & Effect is the theme of the card. You will get what you deserve, even if you are in a legal side, the deserving side will win. Be watchful of your excretory system; take good care of your health. The finances that flow towards you should be utilized for other people as well rather than just self. Be honest and give each other equal chance to strive in the relationships. This is a point where all your disputes have a high chance to resolve. People who are thinking of legal proceedings must go head."},
                    {"name":"The Hanged Man","imgsrc":"img/Major Arcana Pictures/12. The Hanged Man.jpg","desc":"Go with the flow of water, don’t resist the change. This flow will take you exactly where you need to go by resisting you are only decreasing your chances to reach your goals on time.  In order to gain one thing, some-things will be required to be left behind. To achieve higher, long term plans, what you have in present is just tempting. It is time you move towards something that is more gaining. The old habits need to be replaced with new ones. You need to do things differently and you yourself are that change in your life. "},
                    {"name":"The Death","imgsrc":"img/Major Arcana Pictures/13. The Death.jpg","desc":"A major transformation will happen in your life that cannot be stopped. A transition that is meant to happen and during the phase you might not like it but it is a blessing in disguise. This change was much awaited by your sub conscious. Accept and believe that it will bring you what your true life purpose desires. Give up the way you relate with old things. This is a death of one cycle and beginning of another. Have faith in the process and move on to something more rewarding and challenging. Be grateful that this phase is happening in your life, and you are being transformed."},
                    {"name":"The Temperance","imgsrc":"img/Major Arcana Pictures/14. The Temperance.jpg","desc":"Things will happen at a slow pace on your life right now. Don’t try to rush things into happening. It is time given to you where you heal yourself and prevent yourself from getting into any power, ego struggles. Listen to the harmony in your life, you take one step towards the spirit will take 10 steps towards you. Balance your work and play and know that Divine Timing is at play here. There will be a situation where your mediation will be required so try to understand things and be free of judgment. Make peace with everything. Your power of manifesting will be strong enough to make things happen for you. "},
                    {"name":"The Devil","imgsrc":"img/Major Arcana Pictures/15. The Devil.jpg","desc":"The materialistic bondage is quite a lot in your life. You need to independent yourself. You are trapped in a reality that is fueling your selfishness, egocentric ideas. You need to pull yourself out of it in order to see thing clearly. The power of Karma is strong at this time, every negative thought, every bad intention you will have will be accounted for. It will bring you nothing but harm. Depressive and unsatisfied attitude will be around. This is a situation which needs to be worked out, use your brain and good intentions to do so.  A good omen for marriage!"},
                    {"name":"The Tower","imgsrc":"img/Major Arcana Pictures/16. The Tower.jpg","desc":"What you once thought served you is no longer going to be by your side. There is going to be some ravaging change that cannot be prevented. Sudden disruptive change is bound to happen. The illusions you had about people will fade away. This change may bring pain, shock, hamper your belief system. The situation will not work according to your frame of mind. You have been deluding yourself to be in your comfortable zone but for how long? So consider this as a wake-up call."},
                    {"name":"The Star","imgsrc":"img/Major Arcana Pictures/17. The Star.jpg","desc":"You have it in you to accomplish what you need to, just tune in and you will find your inspiration. Be hopeful and expect things to follow your way. Obstacles will overcome. Hold on to your ideals; strive to give your best. Your desires, wishes will be fulfilled in some much unexpected way. The Star is a indicative of good health. Work on enhancing your spiritual life. This card is always very positive and cheerful; it brings with itself all the accolades to the work you have done. "},
                    {"name":"The Moon","imgsrc":"img/Major Arcana Pictures/18. The Moon.jpg","desc":"Good Omen for those who are in clandestine affair. Don’t let the false information get to you. You are beginning to trust your intuitions but you need to give yourself time to let it develop fully. There are some hidden matters that are yet to come into your light. Refrain from investing at this time. Also your artistic side will be heightened. A deep connection will be developed between people. You will come to know the true self of the other person or your own. You have to be careful to not let your emotional side cloud your judgment. "},
                    {"name":"The Sun","imgsrc":"img/Major Arcana Pictures/19. The Sun.jpg","desc":"The Sun signifies happiness and contentment. Things are going well and you will feel happy and enthusiastic. Recovering to a good health, restoration of energy, brighter days lies ahead. Your vision will get clearer on how to take things forward. You will meet people who will bring out the best in you, so surround yourself with them. You will become consciously aware of the presence of Spirit around you and in everything. You will be an inspiration to many. Take control of your life and lead the way. Reunions, birth, success, celebration, accomplishments."},
                    {"name":"The Judgement","imgsrc":"img/Major Arcana Pictures/20. The Judgement.jpg","desc":"Archangel Gabriel’s association with this card tells you that you will be given the opportunity and be supported in your field. You are at a stage wherein you need to make final decisions. This decision will not only affect your present but your future situation too. You will feel that there is stability on your life, you have finally started to understand yourself. So trust yourself and chose carefully. Career success and enjoyment of past efforts will rock your way. "},
                    {"name":"The Worlds","imgsrc":"img/Major Arcana Pictures/21. The World.jpg","desc":"The completion of a cycle, fulfillment of desires, the best card in the pack.  You have undergone a series of experiences to reach where you are right now. Acknowledge and appreciate yourself for being that way. Be in harmony with times, a relationship will develop at its own pace. You can do anything you wish to because you are in sync with the Universal forces. You continue to do so and you will be in peace and reach your destination without any disruptions. Your personal development is what is more important right now."},
{"name":"The Ace of Pentacles","imgsrc":"img/Pentacles/Pentacles/1 Ace.jpg","desc":"Pentacles suggest money, the beginning of an enterprise that will yield financial rewards. Material, physical comforts will come from this work. Gear up yourself for the new project as it will require your cent percent dedication. You will be supported in your work. The opportunities will knock your door & it is up to you how to utilize them to your favour. On the personal front, you will meet a person who will offer you financial security. You will tend to be practical with the on-goings of the relation. "},
              {"name":"The Two of Pentacles","imgsrc":"img/Pentacles/Pentacles/2.jpg","desc":"It represents that income will flow abundantly towards you but you will be required to carefully balance all of the resources flowing towards you. You might have to juggle a bit with the resources to balance it out. Budget your time & resources. There will be restlessness, impatience. Share your responsibilities with someone. You will notice the progress happening only if you learn to manage your resources. "},  
              {"name":"The Three of Pentacles","imgsrc":"img/Pentacles/Pentacles/3.jpg","desc":"Your will become proficient in your work. Your talent & skills are going to come in handy soon. It will help you rise above others. If you don’t know what your talent is, discover it. This will earn you material comfort. Continue developing your craft, also try to pursue spirituality. New job, new projects anything you take on will prosper."},
              {"name":"The Four of Pentacles","imgsrc":"img/Pentacles/Pentacles/4.jpg","desc":"You will be able to create an empire of your own. You will get to the top of your tier, power position. In some cases, you will be required to defend what you have earned. Inheritance, legacy is possible. You will be able to accumulate as much wealth; you will have a solid financial backing. However, there will be a relationship based on partnership, money & security. It will lack freedom or enthusiasm. This card will help you strengthen your self-worth. "},
              {"name":"The Five of Pentacles","imgsrc":"img/Pentacles/Pentacles/5.jpg","desc":"Be cautious towards your finances. You are on the verge of losing your wealth if you don’t alarm yourself now. An investment made now will not pay off. You need to see a change of work that will offer you better financial security. Detach yourself from people who drain you of your resources. You will not be alone in this misfortune, look in other direction to save yourselves. There is always hope, so open your eyes & accept that you need to change your attitudes."},
              {"name":"The Six of Pentacles","imgsrc":"img/Pentacles/Pentacles/6.jpg","desc":"The past problems are going, someone has offered you help. The scales are balancing. You will encounter a group which will help you a lot in learning how to earn greater profits. This card represents generosity, benevolence. Your debts will be paid off. You will have an equal give and take relationship to follow up with. Be receptive. Charitable attitude will help you the best. "},
              {"name":"The Seven of Pentacles","imgsrc":"img/Pentacles/Pentacles/7.jpg","desc":"This time represents where you need to evaluate your harvest. Your past efforts will pay of you well but you have got to be patient. Even so in your personal life, you might feel things are not turning as you hoped but they will. You have a long road ahead so continue marching success is waiting. Keep developing and watering your self-worth. You will grow at your own pace. "},
              {"name":"The Eight of Pentacles","imgsrc":"img/Pentacles/Pentacles/8.jpg","desc":"For someone who has clear ambition in life this card is very promising. You will find contentment in your field. You have the skills & knowledge to further your achievements. Dedicate yourself towards your passion. Fall in love with your work without any doubts. Learn and equip yourself as much as you can. Be realistic & give sincere efforts. In some cases, a new job and a welcoming of romance is possible. "},
              {"name":"The Nine of Pentacles","imgsrc":"img/Pentacles/Pentacles/9.jpg","desc":"You have worked towards your achievements to reach upto a certain level in your life. You are all worth and deserve this happiness, richness, comfort all around you. Now is the time to enjoy the fruits of your labour. You will have success, recognition in your work life. There will be a sense of fulfillment and security in personal life. No need to worry about financial and materialistic comfort. "},
              {"name":"The Tens of Pentacles","imgsrc":"img/Pentacles/Pentacles/10.jpg","desc":"You have gained confidence, security and have reached to a well deserving position. You may receive inheritance. There will be peace in the family matters. Use this opportunity to help others as well. The support from the family will be your strength. You may also plan to start a family, a wedding; you have reached that point in life where it is safe for you to be thinking about it. People will be inspired from you. "},
              {"name":"The Page of Pentacles","imgsrc":"img/Pentacles/Pentacles/Page.jpg","desc":"It represents the energy of a person who is emotionally independent and less expressive. A person who is more connected to outdoors and prefers to stay alone. It brings in the opportunity wherein you can understand all about finances. It tells about you joining a new work as a beginner. Focus on being financially stable and keep your efforts sincere. Your work will probably be in a health related field or a field where practical working is required. Your approach towards relationships should/will be very simple and practical."},
              {"name":"The Knight of Pentacles","imgsrc":"img/Pentacles/Pentacles/Knight.jpg","desc":"It represents the energy of a person who might not be well seasoned or educated but very reliable and honest and gives work the priority. Financially, you will be able to make an addition to your property. Focus on saving and avoid taking risks with money. You will witness the growth in your income slowly and steadily. As per your traits, it represents someone who will be loyal towards the relationships. Your association will be a secured one and you will focus on financial security and practical outlook."},
              {"name":"The Queen of Pentacles","imgsrc":"img/Pentacles/Pentacles/Queen.jpg","desc":" It represents someone who has a knack for business and is very sensible, mature and proficient in their chosen work. She knows very well how to make good use of the resources. She is respectable because of her wisdom. She is beautiful both inside and outside.  Joining or opening up business ventures will be a good action. She also represents someone who will be on the same page as she is when it comes to dating someone. There will be mutual respect, trust and understanding between two people.  "},
              {"name":"The King of Pentacles","imgsrc":"img/Pentacles/Pentacles/King.jpg","desc":"Jack of all trades is what the King of Pentacles represents.  A person, who is in the organizing level and has a stable career, has determination, courage to excel in his work. It’s important that you understand you capabilities of handling the finances efficiently. A man with honesty and knows to keep up the commitment; though he still needs to work on keeping his love life full of spark.  He will seek the relationship based on status and security and will be very helpful towards the growth of their partner. "},
{"name":"The Ace of Swords","imgsrc":"img/Swords/Swords/1 Ace.jpg","desc":"You have finally gained clarity & mental strength.  You will feel a sense of will power has returned to you. You will break free from previous patterns that were holding you back. There is no looking back now & no stopping you either. You will be successful in all your endeavors. Have faith in your judgments. In personal life, you will find it difficult to have an emotional attachment. You need to be up straight to discuss what you want clearly. Swords are related to your intellect so an upgrade to your education is likely. New ideas will take birth; go ahead with financial matters & an indication to make investments, sign deals."},
                {"name":"The Two of Swords","imgsrc":"img/Swords/Swords/2.jpg","desc":"You will meet someone who will have a mental compatibility with you. You can rely on this person when it comes to work, taking business & financial decisions. Both of you will be helpful to each other to achieve common goals. Formation of alliance, rational outlook, sharing power, resolving issues, moving forward fearlessly are the prime indications. In personal life, you may share a different perspective than the other so a good communication will be required out of you two. A conversation is required to come to a mutual conclusion. "},
                {"name":"The Three of Swords","imgsrc":"img/Swords/Swords/3.jpg","desc":" An end of a relationship, friendships, partnerships, divorce, betrayal. The individuals will go their separate ways to pursue their self-interests. It was an inevitable situation & good for the involved people in longer run. You will come out of the delusion that was blinding you it was giving you false hopes. There will be an end to what no longer serves you & you will have to learn to let go of the situation. There will be a discord which will give you a huge clarity, use that to avoid losses to your personal matters. Cry your heart out, share and do not hold on to grudges, do not try to suppress your emotions. A minor surgery is also indicated."},
                {"name":"The Four of Swords","imgsrc":"img/Swords/Swords/4.jpg","desc":"This is a time to rest, contemplate & introspect. You need to regain your strength & your power back. It is time where you should put everything to rest and reconsider everything that you were doing. Pray, meditate, take a walk, surround yourself with greens, eat well, follow a healthy diet, indulge in self-care. Take a vacation, recharge, refocus yourself. You will gain inspiration & a new insight. Solitude is the best gift you can bestow upon yourself. Learn to live with yourself, observe & listen to your thoughts. A hospital visit is indicated but could be for other reasons & not related to you. "},
                {"name":"The Five of Swords","imgsrc":"img/Swords/Swords/5.jpg","desc":"You will encounter losses & failure so it is good to change the path you are on because it will bring you nothing but misery. It is time where you accept defeat, swallow your pride & make the changes that are necessary. Don’t continue to indulge yourself in meaningless arguments or fights as it will only further weaken you. A tragedy that has occurred in your life needs not to increase more. Gather yourself, pick up the pieces of your life & begin again. "},
                {"name":"The Six of Swords","imgsrc":"img/Swords/Swords/6.jpg","desc":"Traveling will take you away from the toxic situation that you have been in. It indicates that you distance yourself from people who have been trying to harm you. Get yourself on to a new journey physically or mentally. The past has nothing in store for you now. The destination must be unclear to you but you must go on. Business trips are likely to take place. You need to welcome new ideas, embrace & welcome new people with different perspectives. They will help you come out of the cage of beliefs you were once holding upon to. Your troubles will be resolved."},
                {"name":"The Seven of Swords","imgsrc":"img/Swords/Swords/7.jpg","desc":"You can fix what has been wronged with proper judgment & your cleverness. Don’t think of confronting who have wronged you or cheated you. Use your smartness to deal with them. A favourable turn of events is possible only if you’re willing to rectify your mistakes. You can make a comeback through proper contemplation, whole hearted efforts & by reflecting upon your actions. "},
                {"name":"The Eight of Swords","imgsrc":"img/Swords/Swords/8.jpg","desc":"You have been blinded by false information. You feel trapped because of this muddled thinking that has blocked your senses from seeing the truth. You must open your eyes front & behind to understand what really is going on around you. You have got to have patience to get out of this mess. Give up your false ego & pride & ask for help. You can save yourself from dangers if you act on time."},
                {"name":"The Nine of Swords","imgsrc":"img/Swords/Swords/9.jpg","desc":"It is one of the most difficult cards; it indicates that you’re being self-destructive. Guilt, resentment of some kind is causing you anxiety, sleepless nights. Watch your thoughts as they are demeaning & causing you to undermine your confidence. You must decide to come out of your circumstances with courage or if that can’t be done leave your past behind, don’t dwell on it. You have suffered a great loss. Ladies should watchout for their health. "},
                {"name":"The Ten of Swords","imgsrc":"img/Swords/Swords/10.jpg","desc":"Betrayal & mistrust is making you feel cold. Self doubt & self pity are hovering around you. Yes, being deceived is the worst thing that can happen to someone. But continuing living in that feeling is much worse. Your ideas, plans have been unsuccessful, failure has occurred. You will experience grief & sorrow. Use this failure as a catalyst to rise up again, face your weakness. Since, this is the worst card in the pack, healing will surely follow as you have experienced enough sadness"},
                {"name":"The Page of Swords","imgsrc":"img/Swords/Swords/Page-of-Swords.jpg","desc":"A person who holds grim beliefs; on your face he/she will be what you want them to be but deep inside they hold pessimistic opinions. You should be watchful before placing your trust on someone like that. They might be unsure as to what they want, someone who needs a lot of self-reflection. It represents someone who is aloof, detached. They may have clever mind but the lack of belief & narrow mindset is preventing their growth."},
                {"name":"The Knight of Swords","imgsrc":"img/Swords/Swords/Knight.jpg","desc":"You will encounter a person who will be full of strength & charismatic. This person is too much into themselves; it might appear as though they want to assist you at first but it is otherwise. Refusing to listen to others, being stubborn, arrogant, impatient are some of the traits. In relationships, you need to recognize and break the old patterns of doing. A beginning of a new romance, try not to be too harsh towards your partner. Don’t stamp your experience on them."},
                {"name":"The Queen of Swords","imgsrc":"img/Swords/Swords/Queen.jpg","desc":"A stern person, female probably who is authoritative & has a great influence on the querent. She seeks no harm but could be selfish. She is a seeker of truth, justice. Try to stay true to your financial dealings, any bungling will get you caught. You will feel your situation is too restrictive because of the old traditions. You will feel the influence so strong that it will cloud your judgment. She knows how to get into the minds of people & use to her own interest.  The energy of the card tells you to be strong, rational while making decisions. Take control of your life & decide for yourself."},
                {"name":"The King of Swords","imgsrc":"img/Swords/Swords/King.jpg","desc":"This represents an intelligent man who has gained the position in his life based on his smart approach. He knows how to hold back his real emotions & feelings. This person has a hold on the querent’s life. Could be a father, husband, employer, teacher, friend etc. He will keep his interests before yours. He likes a connection that is based on abstractions that deep feelings. The fear of losing the connection makes him do so. Keep your plans to yourself. This man has a leadership qualities, law, communication, education are his fields of interest. He is an example of how to have strong mental powers."},
{"name":"The Ace of Wands","imgsrc":"img/Wands/Wands/1 Ace.jpg","desc":"A new phase in your life is beginning. It is an opportunity wherein you can lay a firm foundation for your future. An excellent time to make investments, open a new business. This opportunity will stir your talents and your imagination. Same goes for your personal life as well. There will be a spark in the connection you will have. There isn’t a need to give it a second thought. You must make a move. "},
            {"name":"The Two of Wands","imgsrc":"img/Wands/Wands/2.jpg","desc":"You will have a happy successful partnership. A merger, a venture will prove to be beneficial. However, you need to let go the need to control. Be clear about your goals and your purpose. Have a vision, a long term plan and it will be done. There will be a development in the work space. Continue to have the enthusiasm. Take a step ahead and execute your plans. "},
            {"name":"The Three of Wands","imgsrc":"img/Wands/Wands/3.jpg","desc":"You are ready to expand your empire. It is time to take your work to the next level. This is a card of luck and all your worries will soon be over. Patience is the word that you need to imply in your life at this time. You can inspire others.  Be honest with the people in your life, tell them how you feel. This card also tells that it is time to make a commitment, a marriage proposal. "},
            {"name":"The Four of Wands","imgsrc":"img/Wands/Wands/4.jpg","desc":"This card signifies a time of successful conclusion of a project, a time when you will reap the rewards of your efforts. You can buy a new house, relocate. This card tells of material well-being of a person. You will have stability, contentment. You will feel that you are in good place in your life. 	"},
            {"name":"The Five of Wands","imgsrc":"img/Wands/Wands/5.jpg","desc":"There will be a conflict and dispute over a property, finances, or business. Take care of the financial matters on your own. There will be a situation that will be challenging and competitive and you will be required to prove your worth. Make sure you don’t let your ego come in between your interests. Also it is a good time to make negotiations. "},
            {"name":"The Six of Wands","imgsrc":"img/Wands/Wands/6.jpg","desc":"A very important work of yours will be fulfilled. Major ambitions, targets will be fulfilled. Your dreams will be fruitful. You have worked good and you will be successful even though you may worry about it. On personal front also, you will develop co-operation and mutual understanding. You will find love. Be strong and confident. It will pay you off very well."},
            {"name":"The Seven of Wands","imgsrc":"img/Wands/Wands/7.jpg","desc":"This a time where you should not give up what you have stood for all your life. This is a time wherein you need to stand for what you believe in. Your inner determination and conviction will help you win this situation. Don’t let anyone sway you away. It appears tough on the outside but you must continue to stand firm. "},
            {"name":"The Eight of Wands","imgsrc":"img/Wands/Wands/8.jpg","desc":"A communication that you have been waiting for will happen finally. Swift resolution of troubles. An urgent traveling, results will be out soon. A lot of things will happen suddenly in your life and you will be grateful that it did. This is a time to take action and you must not delay. A sudden change in life that will make you work a lot and round the clock. "},
            {"name":"The Nine of Wands","imgsrc":"img/Wands/Wands/9.jpg","desc":"Be self-reliance, you have it in you to keep up your position. In the times of stress, the appearance of this card tells that you need not worry. Stay confident, whatever has been lost will be recovered. Have an understanding of the situation; you have done your best. The losses you experienced in past will be recovered. Be patient and wait for the results. "},
            {"name":"The Ten of Wands","imgsrc":"img/Wands/Wands/10.jpg","desc":"You have developed some kind of pressure and attachment with someone that is now causing you trouble. Responsibilities take a toll on you at the cost of your health. It is time you let go off the unnecessary burdens and obligations. You must redefine the course of action you want to take to achieve balance with work. Share your work load with other people as well. Don’t take up too much emotional burden on yourself."},
            {"name":"The Page of Wands","imgsrc":"img/Wands/Wands/Page.jpg","desc":"It reflects a person who is not too sure of what they are going to do next but holds good intentions. A very exciting opportunity will come your way that will require you to show up your talents. A right time to gather your focus and invest your energy in the line of work that interests you. The page of wands reflects a person who is a good friend and has an energy that can spark your creativity and will put you on your path."},
            {"name":"The Knight of Wands","imgsrc":"img/Wands/Wands/knight.jpg","desc":"It is time you have a long term goal, the Knight of wands brings with himself the possibility of achieving the long-term plans now. You must enact now and let his energy help you envision your plans. There is huge possibility of traveling. It is time you start making changes that you wanted to. There is a massive shift happening in your life which involves movement. "},
            {"name":"The Queen of Wands","imgsrc":"img/Wands/Wands/Queen.jpg","desc":"A strong energy of courage, wisdom will swipe you off your feet. This is the time wherein you will be supported while making investments. A wise person will come in your contact whose presence will help you connect with rightful people in your life. You will no longer feel stuck as this is where right people will walk in your life who will encourage you and help you settle down. Open yourself to their help and trust her guidance. The Queen speaks from her experience when it comes to walking on the path of inspired creativity. "},
            {"name":"The King of Wands","imgsrc":"img/Wands/Wands/King.jpg","desc":"There comes a person in your life who can be called jack of all trades. His advice should be taken into consideration. His knack for being able to understand everything precisely will give you an edge for accomplishing your purpose. Presence of this card is a very auspicious sign as it will help you make a right, wise decision. The maturity & sensibility that comes along with this card will help you in your personal life as well. You will be able to see the right intentions, motive behind everything that was hidden from you till now."}
] ;
    var numbers = new Array();
    for(var i=0;i<78;i++){
            numbers.push(i); 
    }
    function shuffle(o) {
        for(var j, x, i = o.length; i; j = parseInt(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);
        return o;
    }
    if (performance.navigation.type == performance.navigation.TYPE_RELOAD) {
        x = (localStorage.getItem("Cards")).split(",").map(Number);
        
        console.info( "This page is reloaded" );
      } else {
            x = shuffle(numbers);
            localStorage.setItem("Cards",x);
    
        console.info( "This page is not reloaded");
      }

      console.log(x);
    
for(var i=0;i<6;i++){
    
    
    $('#Cards').prepend('<div class="col-md-12 col-sm-12 col-xs-12"> '+
                            '<div class="featured-item">'+
                               '<div class="thumb col-md-4 col-xs-12 col-sm-12" >'+
                                    '<img src="'+ myCards[x[i]].imgsrc  + '"/>'+
                                '</div>'+
                                '<div class="down-content col-md-8 col-xs-12 col-sm-12">'+
                                   '<h4>' +(6-i)+'. ' + myCards[x[i]].name +'</h4>'+
                                    '<p>'+myCards[x[i]].desc + '</p>'+
                                '</div>'+
                            '</div>'+
                        '</div>' 
    );
}
   
var scroll = document.getElementById("scrollTop");

// When the user scrolls down 200px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 200 || document.documentElement.scrollTop > 200) {
    scroll.style.display = "block";
  } else {
    scroll.style.display = "none";
  }
}

    $("#scrollTop").click(function(){
        document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
    })


    /*
    $("#deck_btn").click(function(){
        $("#hid").slideToggle("slow");
    });
  

    $('#cup').click(function(){
        deck=0;
        localStorage.setItem("Deck",deck);
        location.reload();
    });
    $('#mar').click(function(){
        deck=1;
        localStorage.setItem("Deck",deck);
        location.reload();
    });
    $('#pen').click(function(){
        deck=2;
        localStorage.setItem("Deck",deck);
        location.reload();
    });
    $('#swd').click(function(){
        deck=3;
        localStorage.setItem("Deck",deck);
        location.reload();
    });
    $('#wnd').click(function(){
        deck=4;
        localStorage.setItem("Deck",deck);
        location.reload();
    });
    */


    var width = $(window).width(); 

    if (width < 700  ) {
        $('.thumb').css("margin-left","20%");
        $('.thumb').css("min-width","70%");
        $('.thumb').css("min-height","50%");
        $('.thumb').css("margin-top","10%");
      

    }
    else {
        $('.featured-item').css("display","inline-flex");
    }
});

